name: json_stream
description: A package for converting objects to JSON asynchronously through a byte stream.
version: 1.0.0+1
repository: https://github.com/PixelToast/json_stream

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  async: ^2.10.0
  typed_data: ^1.3.1

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^2.0.0
  test: ^1.21.0
